#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: service-one
#        uri: lb://service-one # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
#        predicates:
#          - Path=/service-one/**
#      - id: service-two
#        uri: lb://service-two
#        predicates:
#          - Path=/service-two/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


# 集成Oauth2
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8300/uaa/principal
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


