spring:
  redis:
    port: 6379
    database: 4
    host: 192.168.137.66
    password: 123456
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin