spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      # 配置路由，服务从nacos 中心中获取
      routes:
      - id: service-one
        uri: lb://service-one  # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
        order: 8000
        predicates:
          - Path=/service-one/**
      - id: service-two
        uri: lb://service-two
        order: 8001
        predicates:
          - Path=/service-two/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

# eureka 注册中心
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true


# 集成Oauth2
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8300/uaa/principal

