spring:
  redis:
    port: 6379
    database: 4
    host: 120.77.254.22
    password: 12345678
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin