spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.180.132:26379,192.168.180.132:26380,192.168.180.132:26381
    port: 6379
    database: 4
#    host: 192.168.180.132
#    password: 123456
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin