spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  application:
    name: stone-jta
server:
  port: 9003
  servlet:
    context-path: /stone-jta