spring:
  #主数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.180.134:3306/stone_business?zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      filter:
        wall:
          config:
            multi-statement-allow: true
  redis:
    port: 6379
    database: 4
    host: 192.168.180.134
    password: 123456
dubbo:
  registry:
    address: zookeeper://192.168.180.134:2181
  application:
    name: user-center
    qos-enable: false
  protocol:
    port: 30012
    name: dubbo
  consumer:
    check: false
    timeout: 3000
    version: 1.0.0
  provider:
    timeout: 3000
    version: 1.0.0
logging:
  level:
    com.zhcx.business.basedata.infrastructure.mapper: debug
swagger:
  title: 接口文档
  enabled: true