#spring:
#  # 基于内存的 ActiveMq
#  activemq:
#    in-memory: true
#    # 不使用连接池，如果使用连接池还需要在 pom 中添加 activemq-pool 的依赖
#    pool:
#      enabled: false

# 独立的 ActiveMq
spring:
  activemq:
    broker-url: tcp://192.168.180.132:61616
    user: admin
    password: admin
    close-timeout: 15s   # 在考虑结束之前等待的时间
    in-memory: true      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
    queue-name: sms.queue
    topic-name: sms.topic
    packages:
      trust-all: true
    pool:
      enabled: false
  jms:
    pub-sub-domain: true