spring:
  redis:
    port: 6379
    sentinel:
      nodes: 172.16.102.104:26379,172.16.102.104:26378,172.16.102.104:26377
      master: mymaster
    database: 3
    jedis:
      pool:
        max-active: 20
        max-wait:
          2000
        max-idle: 100
        min-idle: 10
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8801
  nacos:
    discovery:
      namespace: f4ec8ee3-b06c-4b61-b7ea-ac9b00a5a0b2