spring:
  security:
    oauth2:
      client:
        registration:
          web:
            client-id: web
            client-secret: 123456
            #token有效期 单位:秒  当前值：24小时
            access-token-validity-seconds: 86400
            #refreshToken有效期 单位:秒  当前值：7天
            refresh-token-validity-seconds: 604800
            authorization-grant-type: password,refresh_token,authorization_code
            scope: any
            client-name: web端
          app:
            client-id: app
            client-secret: 123456
            #token有效期 单位:秒  当前值：24小时
            access-token-validity-seconds: 86400
            #refreshToken有效期 单位:秒  当前值：7天
            refresh-token-validity-seconds: 604800
            authorization-grant-type: password,refresh_token,authorization_code
            scope: any
            client-name: app端