spring:
  application:
    name: service-two
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.102.152:8848
        namespace: f4ec8ee3-b06c-4b61-b7ea-ac9b00a5a0b2
server:
  port: 8002
  servlet:
    context-path: /service-two


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    