spring:
  application:
    name: service-two
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: b03acc92-d77d-4ca6-aa8c-99291a520839
server:
  port: 8002
  servlet:
    context-path: /service-two


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    