spring:
  application:
    name: service-one
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: b03acc92-d77d-4ca6-aa8c-99291a520839
server:
  port: 8001
  servlet:
    context-path: /service-one
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-field: logic_del