spring:
  #主数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://172.16.102.107:3388/zhcx_business_platform_basedata?zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: test
      password: test123
      filter:
        wall:
          config:
            multi-statement-allow: true
  redis:
    sentinel:
      master: mymaster
      nodes: 172.16.102.104:26379,172.16.102.104:26378,172.16.102.104:26377
    port: 6379
    database: 4
  kafka:
    bootstrap-servers: 172.16.102.104:9092,172.16.102.104:9093,172.16.102.104:9094
    consumer:
      group-id: wisdombus-log-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-commit-interval: 1000
    listener:
      missing-topics-fatal: false
dubbo:
  registry:
    address: zookeeper://172.16.102.11:2181?backup=172.16.102.12:2181,172.16.102.13:2181
    file: /@artifactId@/dubbo-registry/dubbo.cache
  application:
    name: @artifactId@
    qos-enable: false
  protocol:
    port: 30111
    name: dubbo
  consumer:
    check: false
    timeout: 3000
    version: 1.0.0
  provider:
    timeout: 3000
    version: 1.0.0
logging:
  level:
    com.stone.mapper: debug
swagger:
  title: 基础设施管理接口文档
  enabled: true

##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://172.16.102.107:3388/qr_cxpay?zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: test
#      password: test123
#    slave2:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://172.16.102.107:3388/wisdombus2.0_bus_time?zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: test
#      password: test123