spring:
  #主数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/stone_business?zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: sasa
      filter:
        wall:
          config:
            multi-statement-allow: true
  redis:
    port: 6379
    database: 4
    host: localhost
dubbo:
  registry:
    address: zookeeper://localhost:2181
    file: /@artifactId@/dubbo-registry/dubbo.cache
  application:
    name: @artifactId@
    qos-enable: false
  protocol:
    port: 30011
    name: dubbo
  consumer:
    check: false
    timeout: 3000
    version: 1.0.0
  provider:
    timeout: 3000
    version: 1.0.0
logging:
  level:
    com.zhcx.business.basedata.infrastructure.mapper: debug
swagger:
  title: 接口文档
  enabled: true